### ISSUE TITLE
Missing breaking changes in v2.0.0 changelog.

### ISSUE THREAD

**Issue by davidesigner** [epicweb-dev/totp#13]
Hi there,

I think you've forgotten to inform us of an important change in v2.0.0: the name of the algorithm option has changed from `SHA1` / `SHA256` / etc. to `SHA-1`, `SHA-256`, etc.

PS: I also see that your README and some of your comments in the source code refer to the old format.

✌️

**Comment by kentcdodds** [comment]
Thanks! Release notes updated. Would you like to make a pull request for the readme?

**Comment by davidesigner** [comment]
Thanks @kentcdodds, here is the PR: https://github.com/epicweb-dev/totp/pull/14
