### ISSUE TITLE
Support for non-ESM projects

### ISSUE THREAD

**Issue by moishinetzer** [epicweb-dev/totp#3]

**Comment by kentcdodds** [comment]
I'll not be adding support for non-ESM. However, you can use this in CJS projects:

```js
const { generateTOTP, getTOTPAuthUri, verifyTOTP } = await import('@epic-web/totp')
```

Would you be interested in adding a little mention of that in the docs?

**Comment by moishinetzer** [comment]
Yup for sure I can!

**Comment by moishinetzer** [comment]
Top level dynamic imports aren't supported in remix v1 (they will be in v2), are there any other ways you think can be used as a workaround for remix projects still compiling to cjs? (Including in the serverBundle does't work either for some reason.)

Without adding to the server bundle:

```ts
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/Documents/Repos/capply/node_modules/@epic-web/totp/index.mjs not supported.
Instead change the require of /Users/Documents/Repos/capply/node_modules/@epic-web/totp/index.mjs to a dynamic import() which is available in all CommonJS modules.
```
After adding to server bundle:

```ts
import_thirty_two.default.encode is not a function
TypeError: import_thirty_two.default.encode is not a function
```

**Comment by kentcdodds** [comment]
You can't do top-level await in CJS modules. So instead you can simply import where you're using it. For example, here's where we use this in the epic stack:

https://github.com/epicweb-dev/epic-stack/blob/f6f12452afc9d2e670c039ffdbfe2d6402683e52/app/routes/_auth%2B/verify.tsx#L118

```tsx
import { generateTOTP, verifyTOTP } from '@epic-web/totp'

// ...

export async function prepareVerification(/* stuff */) {
// ...
	const { otp, ...verificationConfig } = generateTOTP({
		algorithm: 'SHA256',
		period,
	})
// ...
}
```

To make this work in CJS, you can do this:


```tsx

// ...

export async function prepareVerification(/* stuff */) {
// ...
	const { generateTOTP } = await import('@epic-web/totp')
	const { otp, ...verificationConfig } = generateTOTP({
		algorithm: 'SHA256',
		period,
	})
// ...
}
```

Better idea is to upgrade to ESM.
